version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    networks:
      - proxy
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - /var/nginx-proxy-manager:/data
      - /etc/letsencrypt:/etc/letsencrypt
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  proxy:
    driver: overlay
